language: node_js
sudo: required
node_js:
  - '4.3.2'
env:
  - CXX=g++-4.8 DISPLAY=':99.0' COVERAGE=true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

before_script:
  - "sh -e /etc/init.d/xvfb start -extension RANDR"
  - sleep 3

after_success:
  - npm run coveralls
