language: node_js
sudo: required
node_js:
  - '4.3.2'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

before_script:
  - "export DISPLAY=':99.0'"
  - "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
