language: node_js
sudo: required
node_js:
  - '4.3.2'
env:
  - CXX=g++-4.8 DISPLAY=':99.0' COVERAGE='travis'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

before_script:
  - "sh -e Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +extension RANDR +render -noreset"
  - sleep 3

after_success:
  - npm run coverage
