language: node_js
sudo: required
node_js:
  - '4.3.2'
env:
  - CXX=g++-4.8 DISPLAY=':99.0'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/electron_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 +extension RANDR
  - sleep 3

after_success:
  - npm run coverage
